Name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # هذه هي الخطوة الجديدة لاستخراج المفتاح فوراً
      - name: Extract SHA1
        run: |
          echo "--- GOOGLE_AUTH_KEY_START ---"
          keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android | grep SHA1
          echo "--- GOOGLE_AUTH_KEY_END ---"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6

      - name: Install dependencies
        run: flutter pub get

      - name: Create local.properties
        run: echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Clean Project
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
